version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: react-redux
    versions:
    - 7.2.2
    - 7.2.3
  - dependency-name: react-infinite-scroll-component
    versions:
    - 5.1.0
    - 6.0.0
  - dependency-name: react-spinners
    versions:
    - 0.10.4
  - dependency-name: next-offline
    versions:
    - 5.0.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: redux
    versions:
    - 4.0.5
